services:
  - type: web
    name: fastapi-backend
    runtime: python
    buildCommand: "pip install -r api/requirements.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    workingDir: api
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false
